//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkHeart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public long Id { get; set; }
        public string BookName { get; set; }
        public string Title { get; set; }
        public string body { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string Type { get; set; }
        public string Character { get; set; }
        public int Grade { get; set; }
        public int Focus_count { get; set; }
        public int Comment_count { get; set; }
        public long Word_count { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int GroupId { get; set; }
        public string Url { get; set; }
        public string ImageCover { get; set; }
    }
}
